import fs from "fs";
import path from "path";

// The sticker has two QR codes:
//   - LEFT:  a public URL, e.g. https://truelink.et/TL-0001 (contains the real ID)
//   - RIGHT: an opaque 6-character code, e.g. "778LM0" (NOT derivable from the ID -
//            it only maps back via id_token_mapping.csv, generated by the sticker script)
//
// This file lets the app resolve either QR type back to the real outlet ID.

const MAPPING_PATH = path.join(process.cwd(), "data", "id_token_mapping.csv");

let cachedMapping = null; // Map<code, id>
let cachedMtimeMs = null;

function loadMapping() {
  try {
    const stat = fs.statSync(MAPPING_PATH);
    if (cachedMapping && cachedMtimeMs === stat.mtimeMs) {
      return cachedMapping; // unchanged since last read
    }
    const raw = fs.readFileSync(MAPPING_PATH, "utf-8");
    const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);
    const map = new Map();
    // header: ID,left_qr_url,right_qr_code
    for (const line of lines.slice(1)) {
      const [id, , code] = line.split(",");
      if (id && code) {
        map.set(code.trim().toUpperCase(), id.trim());
      }
    }
    cachedMapping = map;
    cachedMtimeMs = stat.mtimeMs;
    return map;
  } catch (err) {
    return new Map(); // mapping file not present yet - code lookups just won't resolve
  }
}

/**
 * Resolves whatever text was scanned into a canonical outlet ID.
 * Returns { id, source, matched } where:
 *   - source is "url" or "code"
 *   - matched is false if it looked like a right-QR code but wasn't found
 *     in id_token_mapping.csv (e.g. mapping file missing or out of date)
 */
export function resolveScannedText(rawText) {
  const text = rawText.trim();

  // Try URL form first (left QR)
  try {
    const url = new URL(text);
    const segments = url.pathname.split("/").filter(Boolean);
    if (segments.length > 0) {
      return { id: segments[segments.length - 1], source: "url", matched: true };
    }
  } catch (err) {
    // not a URL - fall through, treat as a right-QR code
  }

  const mapping = loadMapping();
  const normalized = text.toUpperCase();
  if (mapping.has(normalized)) {
    return { id: mapping.get(normalized), source: "code", matched: true };
  }

  // Unrecognized code - mapping file may be missing/stale. Surface the raw
  // text so staff can see what was scanned and decide how to proceed.
  return { id: text, source: "code", matched: false };
}


